<?php
/*
 * Generated by Template Debugger
 * https://wordpress.org/plugins/quick-edit-template-link/
 *
 * Child Theme created for $parent
 * Created by $author - $author_uri
 * Theme: $name
 * */

/**
 * Import Parent Theme stylesheet
*/
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
}

